#! /bin/bash
<< Script_Information
Updated: May-2026
Purpose: Script used for Starting the Integrity Hash application

This script will Start the Integrity Hash frontend app and the local File-Integrity Scannner backend.
In addition - it will validate the SHA256 hashes of those two artifacts. Integrity Hash is a completly
offline application. PWSS Values the privacy and integrity of your private files.

Script Version:1.3.2
Script_Information
start_local_server_in_background(){
file_path=${integrity_hash_app_folder}"/local_backend/File-Integrity-Scanner-1.8.5.jar"
expected_hash="ae8b2900e402a24268c5b1e31c49f1e613dfc3c27013bc98851d9dcfe3b762be"
check_file_hash "$file_path" "$expected_hash"
java -jar "$file_path" &

pid=$!
echo "Local backend Java app started with PID $pid"
}

start_frontend_app(){

file_path=${integrity_hash_app_folder}"/frontend/integrity_hash-1.2.3.jar"
expected_hash="e04ca51dde652cc70db6cdb96e0baca591e3bdc76dafd117cb21804a23c9e5d8"
check_file_hash "$file_path" "$expected_hash"
# Set working directory to the frontend app
cd ${integrity_hash_app_folder}"/frontend"
java -jar "$file_path"
}

check_file_hash() {
    local file_path="$1"
    local expected_hash="$2"

    # Calculate the SHA-256 hash of the file
    actual_hash=$(sha256sum "$file_path" | awk '{print $1}')

    # Compare the calculated hash with the expected hash
    if [ "$actual_hash" != "$expected_hash" ]; then
        echo "Hash mismatch! The file has been tampered with or is incorrect."
        echo "Expected: $expected_hash"
        echo "Actual:   $actual_hash"
        exit 1
    else
        echo "The file's SHA-256 hash matches the expected value. Proceeding..."
    fi
}

# Check if something is running on port 15400
if ss -tuln | grep ':15400'; then
    echo "A process is running on port 15400."
    start_frontend_app
else
    echo "No process is running on port 15400."
    start_local_server_in_background
    start_frontend_app
fi

